version: '3.7'

services:
  markie:
    container_name: 'markie_container'
    image: 'markie'
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - "80:80"
    depends_on:
      "postgres":
        condition: service_healthy
    networks:
      - markie-network

  postgres:
    container_name: 'postgres_container'
    image: postgres
    environment:
      POSTGRES_PASSWORD: balonka
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - markie-network
    volumes:
      - postgres:/var/lib/postgresql/data 

networks:
  markie-network:
    driver: bridge

volumes:
  postgres: